version: '3'
services:
  db:
    image: postgres
    container_name: postgres-web
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_USER=app
      - POSTGRES_DB=movies_database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    container_name: Django
    build:
      context: .
    volumes:
      - static_volume:/app/static
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/data/static:ro
    depends_on:
      - backend
    ports:
      - "8001:80"

volumes:
  static_volume: